# Generated by Django 3.0.3 on 2020-02-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
