# Generated by Django 3.0.3 on 2020-02-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authenticatedbyp',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.IntegerField(blank=True),
        ),
    ]
