# Generated by Django 3.0.3 on 2020-02-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0003_auto_20200222_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Date_of_Birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
