# Generated by Django 3.0.3 on 2020-02-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0004_auto_20200222_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(default=1212, max_length=12),
            preserve_default=False,
        ),
    ]
