# Generated by Django 3.0.3 on 2020-02-22 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0005_auto_20200222_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing_obj',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
