# Generated by Django 3.0.3 on 2020-02-22 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0006_missing_obj_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missing_obj',
            old_name='user',
            new_name='complainant',
        ),
        migrations.AddField(
            model_name='murder',
            name='dead_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='murder',
            name='location',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='murder',
            name='suspects',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='miss_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missdate', models.DateField()),
                ('reported_on', models.DateTimeField(auto_now_add=True)),
                ('miss_name', models.CharField(max_length=100)),
                ('pdescription', models.TextField()),
                ('last_seen_loc', models.TextField()),
                ('complainant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_on', models.DateTimeField(auto_now_add=True)),
                ('victim_name', models.CharField(max_length=60)),
                ('s_description', models.TextField()),
                ('suspects', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('complainant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
